In [2]:
import torch
import numpy as np

In [11]:
# Create Tensor from List
data=[[1,2,], [3,4]]
x_data = torch.tensor(data)

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
data

[[1, 2], [3, 4]]

In [7]:
np_array = np.array(data)

In [8]:
np_array

array([[1, 2],
       [3, 4]])

In [12]:
# Create Tensor from numpy array
x_np = torch.from_numpy(np_array)

In [13]:
x_np

tensor([[1, 2],
        [3, 4]])